In [1]:
from pandas.tools.plotting import scatter_matrix
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression as PLS
import numpy as np
#%matplotlib inline

df = pd.read_csv("wine.data.txt", sep=",", skipinitialspace=True, skiprows=0, header=None)

In [2]:
x = df.as_matrix()[:,1:]
y = df.as_matrix()[:,0]

In [4]:
pca = PCA(n_components=2)
X_r = pca.fit(x).transform(x)
X_r

array([[ -3.18562979e+02,  -2.14921307e+01],
       [ -3.03097420e+02,   5.36471768e+00],
       [ -4.38061133e+02,   6.53730945e+00],
       [ -7.33240139e+02,  -1.92729032e-01],
       [  1.15714285e+01,  -1.84899946e+01],
       [ -7.03231192e+02,   3.32158674e-01],
       [ -5.42971581e+02,   1.35189666e+01],
       [ -5.48401860e+02,  -1.14494324e+01],
       [ -2.98036863e+02,   8.18015784e+00],
       [ -2.98049553e+02,   7.10154294e+00],
       [ -7.63079712e+02,   8.33431723e+00],
       [ -5.32943228e+02,   1.42876338e+01],
       [ -5.72834410e+02,   2.10050143e+01],
       [ -4.02925358e+02,   1.61026352e+01],
       [ -8.00053394e+02,   1.21184472e+01],
       [ -5.63245578e+02,  -2.21482866e+00],
       [ -5.33379651e+02,  -1.08048022e+01],
       [ -3.83317591e+02,  -8.47741982e+00],
       [ -9.33118387e+02,   8.35447844e+00],
       [ -9.84031775e+01,  -1.43926594e+01],
       [ -3.35935940e+01,  -2.55679565e+01],
       [ -2.31464375e+01,  -1.81747309e+00],
       [ -

In [5]:
for c, i, target_name in zip("rgb", ["1","2","3"], ["1","2","3"]):
    plt.scatter(X_r[y == i, 0], X_r[y == i, 1], c=c, label=["1","2","3"])
plt.legend()
plt.title('PCA of Wine')

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  from ipykernel import kernelapp as app
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: using a boolean instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


In [6]:
covmat = np.cov(x.T)

In [7]:
w,v = np.linalg.eig(covmat)
w,v = zip(*sorted(zip(w, v)))

In [8]:
w

(0.0082037031417758789,
 0.021072366149372621,
 0.037575978866196159,
 0.07170260316211402,
 0.11209676473741995,
 0.15138126638308474,
 0.27897352306606482,
 0.84106386945518774,
 1.2288452283714257,
 4.9911786076419284,
 9.4381137034706502,
 172.53526647789155,
 99201.789517480982)

In [9]:
v

(array([-0.00232714, -0.01510035,  0.29139846,  0.87889369, -0.33174705,
         0.00273961,  0.11283651, -0.08128692, -0.09902908, -0.00463294,
        -0.05035557, -0.00981967, -0.02314712]),
 array([ -1.71380037e-04,   7.62673115e-04,  -2.59776624e-02,
         -6.00349446e-02,  -5.15240771e-02,  -2.37761666e-02,
         -3.08198127e-02,  -2.95190435e-03,   3.30651238e-02,
         -1.66550828e-01,  -9.75561893e-01,   9.75106606e-02,
         -3.84698250e-02]),
 array([ -7.04931645e-04,   3.49536431e-03,  -7.03239693e-02,
         -1.78200254e-01,  -2.60639176e-01,   2.88912753e-01,
         -1.01973518e-01,  -1.86714531e-01,  -8.73746543e-01,
          4.41922433e-02,  -1.16302516e-02,   2.84851062e-02,
          1.70170830e-02]),
 array([ -9.99822937e-01,   1.77738095e-02,   4.52868159e-03,
         -3.11291570e-03,   2.29856939e-03,  -1.21225507e-03,
          1.07618923e-03,   1.03409482e-05,  -7.25585209e-05,
          3.62670135e-05,   9.99995129e-05,  -2.40452216e-04,
     

In [10]:
for i in range(3):
    eigenv = w[i]
    y = v[i]
    x = np.arange(len(y))
    plt.stem(x, y, linefmt='b-', markerfmt='bo', basefmt='r-')
    plt.show()