In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
def readTrainingData():
    df = pd.read_csv("pubfig_dev_50000_pairs.txt", sep="\t", skipinitialspace=True, skiprows=1, header=None)
    return df

def readValidationData(number):
    path = "pubfig_kaggle_"+str(number)
    feature = pd.read_csv(path+".txt", sep="\t", skipinitialspace=True, skiprows=2, header=None)
    label = pd.read_csv(path+"_solution.txt", sep=",", skipinitialspace=True, skiprows=0)
    return feature,label["Prediction"]

def readMatchingData():
    df = pd.read_csv("pubfig_attributes.txt", sep="\t", skipinitialspace=True, skiprows=2, header=None)
    return df

def readEvalData():
    df = pd.read_csv("pubfig_kaggle_eval.txt", sep="\t", skipinitialspace=True, skiprows=2, header=None)
    return df

def readEvalResult():
    df = pd.read_csv("eval_solution.txt", sep=",", skipinitialspace=True, skiprows=1, header=None)
    return df

In [5]:
train = readTrainingData().as_matrix()
trainX = train[:,1:]
trainY = train[:,0]


In [7]:
import numpy as np
a = np.array([1,2,3,4])
a.reshape(a.size,1)

array([[1],
       [2],
       [3],
       [4]])

In [1]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [2]:
clf.predict([[2., 2.]])

array([1])

In [7]:
import numpy as np
clf.predict(np.array([2,2]).reshape(1,-1))

array([1])

In [8]:
np.array([2,2]).reshape(1,-1).shape

(1, 2)